name: setup
inputs:
  skip-go:
    description: Skip installing Go toolchain
  skip-node:
    description: Skip installing Node.js
runs:
  using: composite
  steps:
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      if: inputs.skip-go == ''
      with:
        go-version-file: go.mod
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      if: inputs.skip-node == ''
      with:
        node-version: '20'
        cache: npm
