name: setup
inputs:
  skip-go:
    description: Skip installing Go toolchain
  skip-node:
    description: Skip installing Node.js
runs:
  using: composite
  steps:
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      if: inputs.skip-go == ''
      with:
        go-version-file: go.mod
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      if: inputs.skip-node == ''
      with:
        node-version: '22'
