name: setup
inputs:
  skip-go:
    description: Skip installing Go toolchain
  skip-node:
    description: Skip installing Node.js
runs:
  using: composite
  steps:
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      if: inputs.skip-go == ''
      with:
        go-version-file: go.mod
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      if: inputs.skip-node == ''
      with:
        node-version: '20'
