name: setup
input:
  skip-go:
    description: Skip installing Go toolchain
  skip-node:
    description: Skip installing Node.js
runs:
  using: composite
  steps:
    # TODO: Remove once setup-go supports reading toolchain line
    - id: toolchain
      run: grep '^toolchain' go.mod | sed 's/^toolchain go/go_version=/' >> "$GITHUB_OUTPUT"
      shell: bash
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      if: inputs.skip-go == ''
      with:
        go-version: ${{ steps.toolchain.outputs.go_version }}
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      if: inputs.skip-node == ''
      with:
        node-version: '20'
        cache: npm
