name: binaries
on:
  workflow_call:
    inputs:
      provenance:
        required: false
        type: boolean
      upload-assets:
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  third-party-licenses:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
        with:
          skip-node: 'true'
      - run: go install github.com/google/go-licenses@v1.6.0
      - name: Download third-party license files
        run: |
          go-licenses save ./... --ignore $(go list -m) --save_path packaging/third-party
          chmod -R u+w packaging/third-party
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: third-party-licenses
          path: packaging/third-party/

  binaries:
    needs: [third-party-licenses]
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04, windows-2025]
    outputs:
      hash-macos-15: ${{ steps.hash.outputs.hash-macos-15 }}
      hash-ubuntu-24.04: ${{ steps.hash.outputs['hash-ubuntu-24.04'] }}
      hash-windows-2025: ${{ steps.hash.outputs['hash-windows-2025'] }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup

      # Install dependencies
      - name: Install cross-compilers
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install g++-aarch64-linux-gnu g++-arm-linux-gnueabihf
      - run: npm ci --ignore-scripts
      # Retrieve third-party license files to include in binary packages
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: third-party-licenses
          path: packaging/third-party/

      # The version of MinGW installed on the windows-2022 runner has a bug in
      # dlltool that breaks passing floating-point parameters to Node, so fetch
      # a newer version.
      # TODO: Remove after upgrading to windows-2025 runner
      - name: Install newer MinGW dlltool
        run: |
          curl -fsSL -o '${{ runner.temp }}\mingw.7z' 'https://github.com/niXman/mingw-builds-binaries/releases/download/14.2.0-rt_v12-rev1/x86_64-14.2.0-release-posix-seh-ucrt-rt_v12-rev1.7z'
          7z x -o'${{ runner.temp }}' '${{ runner.temp }}\mingw.7z'
          echo 'DLLTOOL=${{ runner.temp }}\mingw64\bin\dlltool.exe' >> "$GITHUB_ENV"
        shell: bash
        if: runner.os == 'Windows'

      # Native build, plus tests for good measure
      - name: Build for ${{ (runner.os == 'macOS' && 'arm64') || 'amd64' }}
        run: |
          npx -c 'node-pre-gyp rebuild'
          npx -c 'node-pre-gyp package'
          mkdir binaries
          mv build/stage/*/* binaries
      - run: npm run test
        if: runner.os != 'Windows'
      # Cross builds
      - name: Cross build for amd64
        if: runner.os == 'macOS'
        run: |
          npx -c 'node-pre-gyp rebuild --target_arch=x64'
          npx -c 'node-pre-gyp package --target_arch=x64'
          mv build/stage/*/* binaries
        env:
          CGO_ENABLED: '1'
          GOARCH: amd64
      - name: Cross build for arm
        if: runner.os == 'Linux'
        run: |
          npx -c 'node-pre-gyp rebuild --target_arch=arm'
          npx -c 'node-pre-gyp package --target_arch=arm'
          mv build/stage/*/* binaries
        env:
          CC: arm-linux-gnueabihf-gcc
          CXX: arm-linux-gnueabihf-g++
          CGO_ENABLED: '1'
          GOARCH: arm
      - name: Cross build for arm64
        if: runner.os == 'Linux'
        run: |
          npx -c 'node-pre-gyp rebuild --target_arch=arm64'
          npx -c 'node-pre-gyp package --target_arch=arm64'
          mv build/stage/*/* binaries
        env:
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
          CGO_ENABLED: '1'
          GOARCH: arm64

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: binaries-${{ matrix.os }}
          path: binaries/
      - id: hash
        run: echo "hash-${{ matrix.os }}=$(openssl sha256 -r * | tr '*' ' ' | jq -Rrs @base64)" >> "$GITHUB_OUTPUT"
        shell: bash
        working-directory: binaries

  test-win-binaries:
    needs: [binaries]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - run: npm ci --ignore-scripts
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: binaries-windows-*
          merge-multiple: true
          path: binaries
      - run: mkdir lib && tar xf binaries/win32-x64-napi-v8.tar.gz -C lib
        shell: bash
      - run: node -p "require('.').jsEscaper('<b>')"
        shell: bash
      - run: ./node_modules/.bin/jest -i
        shell: bash

  upload-binaries:
    if: inputs.upload-assets
    needs: [binaries]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: binaries-*
          merge-multiple: true
          path: binaries
      - run: gh release upload '${{ github.ref_name }}' ./binaries/*.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}

  binary-hashes:
    if: inputs.provenance
    needs: [binaries]
    runs-on: ubuntu-24.04
    outputs:
      hashes: ${{ steps.combine.outputs.hashes }}
    steps:
      - id: combine
        run: echo "hashes=$(jq -nr '[env.HASHES|fromjson|.[]|@base64d]|join("")|@base64')" >> "$GITHUB_OUTPUT"
        env:
          HASHES: ${{ toJSON(needs.binaries.outputs) }}

  binary-provenance:
    if: inputs.provenance
    needs: [binary-hashes]
    permissions:
      actions: read
      contents: write
      id-token: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: ${{ needs.binary-hashes.outputs.hashes }}
      provenance-name: binaries.intoto.jsonl

  upload-binary-provenance:
    if: inputs.provenance && inputs.upload-assets
    needs: [binary-provenance]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ needs.binary-provenance.outputs.provenance-name }}
      - run: gh release upload '${{ github.ref_name }}' '${{ needs.binary-provenance.outputs.provenance-name }}'
        env:
          GH_TOKEN: ${{ github.token }}
