name: npm_package
on:
  workflow_call:
    inputs:
      upload-assets:
        required: false
        type: boolean
    outputs:
      artifact-id:
        value: ${{ jobs.npm-package.outputs.artifact-id }}

permissions:
  contents: read

jobs:
  npm-package:
    runs-on: ubuntu-24.04
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
        with:
          skip-go: 'true'
      - run: npm pack
      - id: upload
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: npm-package
          path: go-text-template-napi-*.tgz
      - run: gh release upload '${{ github.ref_name }}' go-text-template-napi-*.tgz
        if: inputs.upload-assets
        env:
          GH_TOKEN: ${{ github.token }}
