name: npm_package
on:
  workflow_call:
    inputs:
      upload-assets:
        required: false
        type: boolean
    outputs:
      artifact-id:
        value: ${{ jobs.npm-package.outputs.artifact-id }}

permissions:
  contents: read

jobs:
  npm-package:
    runs-on: ubuntu-24.04
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup
        with:
          skip-go: 'true'
      - run: npm pack
      - id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: npm-package
          path: go-text-template-napi-*.tgz
      - run: gh release upload '${{ github.ref_name }}' go-text-template-napi-*.tgz
        if: inputs.upload-assets
        env:
          GH_TOKEN: ${{ github.token }}
